// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQRpJvg_L_QTHM5MpUHoUXsYJyEpdPN8',
    appId: '1:195628590555:web:5858de8f396e8c11d8f3fe',
    messagingSenderId: '195628590555',
    projectId: 'fluttersignin-dd1d1',
    authDomain: 'fluttersignin-dd1d1.firebaseapp.com',
    storageBucket: 'fluttersignin-dd1d1.firebasestorage.app',
    measurementId: 'G-GBF0D9FPNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9QIhDCP59CTUfUChrPoXJ4MF3HfqTGPM',
    appId: '1:195628590555:android:c51f1473197f430fd8f3fe',
    messagingSenderId: '195628590555',
    projectId: 'fluttersignin-dd1d1',
    storageBucket: 'fluttersignin-dd1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYoDpozC5DNrRKA24A53_7C6IbIis92l0',
    appId: '1:195628590555:ios:1f54c5d52faeaeadd8f3fe',
    messagingSenderId: '195628590555',
    projectId: 'fluttersignin-dd1d1',
    storageBucket: 'fluttersignin-dd1d1.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYoDpozC5DNrRKA24A53_7C6IbIis92l0',
    appId: '1:195628590555:ios:1f54c5d52faeaeadd8f3fe',
    messagingSenderId: '195628590555',
    projectId: 'fluttersignin-dd1d1',
    storageBucket: 'fluttersignin-dd1d1.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMQRpJvg_L_QTHM5MpUHoUXsYJyEpdPN8',
    appId: '1:195628590555:web:fdad7da9e19d6925d8f3fe',
    messagingSenderId: '195628590555',
    projectId: 'fluttersignin-dd1d1',
    authDomain: 'fluttersignin-dd1d1.firebaseapp.com',
    storageBucket: 'fluttersignin-dd1d1.firebasestorage.app',
    measurementId: 'G-9739S24F7R',
  );

}